import { afterEach, describe, expect, it, vi } from "vitest";
import { submitFeedback } from "../src/feedback/submit";
const config = { publishableKey: "sp_pub_test" as const, endpoint: "http://localhost:8000" };
afterEach(()=>vi.restoreAllMocks());
describe("feedback submission",()=>{
  it("preserves the exact text-only shape",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({submission_id:"s1",status:"accepted"}),{status:202}));await submitFeedback(config,{title:"Broken",description:"It broke",category:"bug"},"00000000-0000-4000-8000-000000000001");const [,init]=fetch.mock.calls[0];const body=JSON.parse(String(init?.body));expect(body.attachments).toBeUndefined();expect(body.idempotency_key).toContain("00000000");expect((init?.headers as Record<string,string>)["X-SpareParts-Publishable-Key"]).toBe("sp_pub_test")});
  it("submits only unique opaque ready IDs at top level",async()=>{const fetch=vi.spyOn(globalThis,"fetch").mockResolvedValue(new Response(JSON.stringify({submission_id:"s1",status:"accepted"}),{status:202}));await submitFeedback(config,{title:"Broken",description:"It broke",category:"bug"},"key",[{id:"a1",name:"x.png",mimeType:"image/png",sizeBytes:2}]);const body=JSON.parse(String(fetch.mock.calls[0][1]?.body));expect(body.attachments).toEqual(["a1"]);expect(JSON.stringify(body)).not.toContain("data:image");expect(JSON.stringify(body)).not.toContain("upload")});
  it("rejects duplicate IDs before network work",async()=>{const fetch=vi.spyOn(globalThis,"fetch");const descriptor={id:"a1",name:"x.png",mimeType:"image/png" as const,sizeBytes:2};await expect(submitFeedback(config,{title:"x",description:"y",category:"bug"},"key",[descriptor,descriptor])).rejects.toThrow("Duplicate");expect(fetch).not.toHaveBeenCalled()});
});
